on: [push]

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    name: A demo job to delete workflow runs
    steps:

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
